// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcGjkp9__OzlSqj-49AWOgOlWPGhS5b5o',
    appId: '1:579750065107:web:35e331396707eea888b526',
    messagingSenderId: '579750065107',
    projectId: 'shoppingcart-9a3c1',
    authDomain: 'shoppingcart-9a3c1.firebaseapp.com',
    storageBucket: 'shoppingcart-9a3c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy31juHpKAsbEhsEHSzzQ_Ibo6iDG-Sis',
    appId: '1:579750065107:android:102458f9d44e5eef88b526',
    messagingSenderId: '579750065107',
    projectId: 'shoppingcart-9a3c1',
    storageBucket: 'shoppingcart-9a3c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYIfceCiHy1RxPPCuy4PWZQ3bswkpuaG8',
    appId: '1:579750065107:ios:6474fcaddc54db9488b526',
    messagingSenderId: '579750065107',
    projectId: 'shoppingcart-9a3c1',
    storageBucket: 'shoppingcart-9a3c1.appspot.com',
    iosClientId: '579750065107-hilsv99kdd0tbv1u677goselcf343kfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYIfceCiHy1RxPPCuy4PWZQ3bswkpuaG8',
    appId: '1:579750065107:ios:6474fcaddc54db9488b526',
    messagingSenderId: '579750065107',
    projectId: 'shoppingcart-9a3c1',
    storageBucket: 'shoppingcart-9a3c1.appspot.com',
    iosClientId: '579750065107-hilsv99kdd0tbv1u677goselcf343kfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcGjkp9__OzlSqj-49AWOgOlWPGhS5b5o',
    appId: '1:579750065107:web:181203bb92816efc88b526',
    messagingSenderId: '579750065107',
    projectId: 'shoppingcart-9a3c1',
    authDomain: 'shoppingcart-9a3c1.firebaseapp.com',
    storageBucket: 'shoppingcart-9a3c1.appspot.com',
  );

}